version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket codepipeline-us-east-1-535604203136 --output-template-file template.yaml
artifacts:
  files:
    - template.yaml